// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJOe9v2ytxy2rDHjNs9gF3s_HcxX6NfVo',
    appId: '1:676046608509:web:2745001840c4395584f914',
    messagingSenderId: '676046608509',
    projectId: 'onshop-f003f',
    authDomain: 'onshop-f003f.firebaseapp.com',
    storageBucket: 'onshop-f003f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ3MSFQMNH2fgffG4h3v8exYnC-kU_e4M',
    appId: '1:676046608509:android:abb7bcef3a51b3d484f914',
    messagingSenderId: '676046608509',
    projectId: 'onshop-f003f',
    storageBucket: 'onshop-f003f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA25VFkfI6Xno5xzf3BQ3FtwXqOKEzSqp4',
    appId: '1:676046608509:ios:9304c33a4fddb71384f914',
    messagingSenderId: '676046608509',
    projectId: 'onshop-f003f',
    storageBucket: 'onshop-f003f.firebasestorage.app',
    iosBundleId: 'com.example.onshopapp',
  );

}